Feature/sp-62-bugs
szczepienia-pw/frontend pull request #23
Opened 2022-03-22 19:54 UTC by megifalko

2022-03-22 20:31 UTC, dvalim requested changes
Nice job, a few details though:

- It would be better to move this dialog into a separate file in the /components folder
- It would be good to test actual functionality and not just opening/closing, for example: open dialog -> input bug info -> click send button -> check if the right request is sent. See the other tests for examples

2022-03-22 20:31 UTC, dvalim commented on src/containers/FooterContainer.vue
> +      :style="{ width: '50vw', height: '65vh', justifyContent: 'space-between' }"
It's better to remove this height, since you can see the background through the 'slots' when the dialog is too high

2022-03-22 20:31 UTC, dvalim commented on src/containers/FooterContainer.vue
> +      </template>
Either remove this template or remove the `header` prop, since they set the same thing

2022-03-22 20:31 UTC, dvalim commented on src/containers/FooterContainer.vue
> +          <label for="desc-input">Bug name</label>
Shouldn't this be `name-input`?

2022-03-22 20:31 UTC, dvalim commented on src/containers/FooterContainer.vue
> +          <label for="name-input">Bug description</label>
Shouldn't this be `desc-input`?

2022-03-22 20:31 UTC, dvalim commented on src/services/api.js
> +        console.log(response);
Probably don't need this console log

2022-03-22 20:34 UTC, dvalim commented on src/containers/FooterContainer.vue
> +      </template>
Should also remove the `footer` prop

2022-03-22 22:07 UTC, dvalim approved these changes

2022-03-22 22:10 UTC, dvalim approved these changes

2022-03-23 07:50 UTC, RazorMeister requested changes
Bug report button should be visible only to logged in users

2022-03-23 07:57 UTC, RazorMeister requested changes

2022-03-23 07:57 UTC, RazorMeister commented on src/components/BugReportDialog.vue
> +            <span class="p-float-label mb-5">
Span shouldn't be used as a container for other elements. You can make there a normal div with styling. Even IDE is badly formatting these elements inside

2022-03-23 07:57 UTC, RazorMeister commented on src/components/BugReportDialog.vue
> +export default {
In other components are short-syntax setup scripts and here u are using this long-syntax setup. Use everywhere only one syntax (imo this shorter is beter)

2022-03-23 07:57 UTC, RazorMeister commented on src/services/api.js
> +        name: name,
If u have same key and value name in the object you can use something like this:
`{ name, description }` and js will automatically convert it to: `{ name: name, description: description }` under the hood.

2022-03-23 08:21 UTC, RazorMeister requested changes
One more thing - spacing. In for example LoginPage there are 2 spaces and in BugReportDialog 4. Keep one styling in whole project.

2022-03-23 10:37 UTC, dvalim approved these changes

2022-03-23 10:37 UTC, merged