[SP-47] Vaccination process
szczepienia-pw/frontend pull request #49
Opened 2022-04-23 14:03 UTC by megifalko

-Add button to mark vaccination as completed

2022-04-23 17:38 UTC, RazorMeister requested changes

2022-04-23 17:38 UTC, RazorMeister commented on src/components/DoctorVaccinationsList.vue
> +                        <Button v-if="data.status === 'Planned'" icon="pi pi-check" class="p-button-success p-button-rounded" @click="confirmVaccination(data)" />
tu cchyba v-else-if uzyc bo raczej nie moze bys status free i planned jednoczesnie

2022-04-23 17:38 UTC, RazorMeister commented on src/components/DoctorVaccinationsList.vue
>                          <Button v-if="data.status === 'Free'" icon="pi pi-trash" class="p-button-danger p-button-rounded" @click="confirmDeleteVaccination(data)" />
Te statusy powinny byc wyniesione do jakiegos enuma zeby uniknac magic stringow w kodzie

2022-04-24 13:00 UTC, dvalim approved these changes

2022-04-24 15:01 UTC, lavar3l requested changes
Szczepienie pacjenta (tj. ustawianie statusu _Completed_) działa poprawnie.
Brakuje natomiast możliwości anulowania wizyty (tj. ustawienia statusu _Canceled_).

Taka możliwość może być potrzeba w sytuacji gdy pacjent nie będzie mógł być zaszczepiony w danym terminie (np. z powodu choroby).

![obraz](https://user-images.githubusercontent.com/57873253/164982728-4b3f2cb5-90ea-47da-a7fd-723352cbfd78.png)
[Request w API](https://battnik90.stoplight.io/docs/io/b3A6NDQ1Nzg0NzA-vaccinate-patient)

2022-04-24 18:39 UTC, lavar3l approved these changes

2022-04-24 20:22 UTC, merged