[SP-173] Fix issues 42,44,45,46,47,48
szczepienia-pw/frontend pull request #50
Opened 2022-04-23 14:58 UTC by dvalim

This closes #42, closes #44, closes #45, closes #46, closes #47 and closes #48.

2022-04-23 16:53 UTC, lavar3l requested changes
Problem z wyświetlaniem sekund lub samego dwukropka nadal występuje przy rejestracji (na etapie potwierdzania wizyty) oraz w szczegółach wizyty.

![obraz](https://user-images.githubusercontent.com/57873253/164915768-128ce19b-da94-4878-bfb8-bdaa0a2cb13f.png)
![obraz](https://user-images.githubusercontent.com/57873253/164915785-808212e6-199d-4b5f-9a01-506da647a5aa.png)

2022-04-23 17:48 UTC, RazorMeister requested changes
Mam dwie strony i po kliknięciu w te dwie strzałki żeby przeskoczyło do ostatnie strony przechodzi na stronę 3 (której nie ma) ale request wysyła jako 2.
![image](https://user-images.githubusercontent.com/19613420/164933726-7f1bbed8-d6a2-40ef-828a-4c4549535b49.png)
![image](https://user-images.githubusercontent.com/19613420/164933737-30527dc6-84c9-4517-9377-569d8709c6dd.png)

2022-04-23 17:51 UTC, RazorMeister requested changes
Mogę zbugować rejestrację na szczepionke:

Przechodze do widoku podsumowania -> klikam wstecz -> nie pojawia się wybrana szczepionka ale przcysik dalej jest aktywny -> klikam dalej (w podsumowaniu nie mam szczepionki) -> klikam akceptuj i blad z backendu bo sie szczepionka nie wysyla:

![image](https://user-images.githubusercontent.com/19613420/164933897-7f70186f-bf89-43ec-9dea-7a52531803e6.png)
![image](https://user-images.githubusercontent.com/19613420/164933898-30161002-bafd-4bfb-984c-7aa950c28247.png)

2022-04-23 20:57 UTC, lavar3l approved these changes

2022-04-24 06:18 UTC, RazorMeister approved these changes

2022-04-24 08:44 UTC, merged