[SP-55] Patient data
szczepienia-pw/frontend pull request #51
Opened 2022-04-23 15:31 UTC by megifalko

-Admin can view patients
-Admin can edit patients
-Admin can delete patients

2022-04-23 16:42 UTC, lavar3l requested changes

2022-04-23 16:42 UTC, lavar3l commented on src/components/PatientDataTable.vue
> +			</div>
Format kodu pocztowego nie jest sprawdzany (tak jak jest przy rejestracji pacjenta).

2022-04-24 05:31 UTC, megifalko commented on src/components/PatientDataTable.vue
> +			</div>
Zrobione :)

2022-04-24 06:16 UTC, RazorMeister approved these changes

2022-04-24 13:02 UTC, dvalim approved these changes

2022-04-24 13:23 UTC, lavar3l approved these changes

2022-04-24 13:39 UTC, merged