[SP-33] Vaccination cerificate
szczepienia-pw/frontend pull request #54
Opened 2022-04-27 07:41 UTC by megifalko

2022-04-27 09:17 UTC, dvalim requested changes

2022-04-27 09:17 UTC, dvalim commented on src/views/patient/VisitHistory.vue
> +  console.log(selectedVaccination.value)
Został jakiś log

2022-04-27 09:17 UTC, dvalim commented on src/views/patient/VisitHistory.vue
> +      loadVaccinationHistory(pagination.value.currentPage);
Nie trzeba przeładowywać, bo niczego nie zmieniliśmy w historii

2022-04-27 09:17 UTC, dvalim commented on src/views/patient/VisitHistory.vue
> -};
Rebase to usunął z jakiegoś powodu

2022-04-27 09:17 UTC, dvalim commented on src/views/patient/VisitHistory.vue
> +        })
To stara wersja tej funkcji

2022-04-27 09:17 UTC, dvalim commented on src/views/patient/VisitHistory.vue
> +      successToast(toast, `Certificate downloaded`);
Tego tosta imo można wywalić, użytkownikowi i tak otwiera się okienko pobierania

2022-04-28 08:56 UTC, dvalim approved these changes

2022-05-03 20:32 UTC, lavar3l approved these changes

2022-05-06 08:14 UTC, merged